"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ZcmOrientusOrientation(object):
    __slots__ = ["roll", "pitch", "heading", "q0", "q1", "q2", "q3"]

    def __init__(self):
        self.roll = 0.0
        self.pitch = 0.0
        self.heading = 0.0
        self.q0 = 0.0
        self.q1 = 0.0
        self.q2 = 0.0
        self.q3 = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmOrientusOrientation._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fffffff", self.roll, self.pitch, self.heading, self.q0, self.q1, self.q2, self.q3))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmOrientusOrientation._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmOrientusOrientation._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmOrientusOrientation()
        self.roll, self.pitch, self.heading, self.q0, self.q1, self.q2, self.q3 = struct.unpack(">fffffff", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmOrientusOrientation in parents: return 0
        tmphash = (0x715c2288e5ebc094) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmOrientusOrientation._packed_fingerprint is None:
            ZcmOrientusOrientation._packed_fingerprint = struct.pack(">Q", ZcmOrientusOrientation._get_hash_recursive([]))
        return ZcmOrientusOrientation._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

